spring.application.name=spring-security-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/Raghav
spring.datasource.username=postgres
spring.datasource.password=Raghav@1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.session.cookie.same-site=strict
